# Generated by Django 3.2.2 on 2021-05-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0002_alter_state_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='function',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='state',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ub.state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ub.activitycategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ub.state'),
        ),
    ]
