# Generated by Django 3.2.2 on 2021-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0004_alter_user_google_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastlink',
            name='button_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fastlink',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
