# Generated by Django 3.2.2 on 2021-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0005_auto_20210508_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
