# Generated by Django 3.2.2 on 2021-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0008_rename_google_token_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
