# Generated by Django 3.2.2 on 2021-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0009_auto_20210513_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='button_label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.TextField(),
        ),
    ]
