# Generated by Django 3.2.2 on 2021-05-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='prompt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
