# Generated by Django 3.2.4 on 2021-06-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0013_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
