# Generated by Django 3.2.4 on 2021-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0016_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unit_name',
            field=models.TextField(),
        ),
    ]
