# Generated by Django 3.2.4 on 2021-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0017_auto_20210606_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='function',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
