# Generated by Django 3.2.4 on 2021-06-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0018_alter_state_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
