# Generated by Django 3.2.4 on 2021-08-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ub', '0020_contactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNameList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
